FranciscoSosa25/CmriSeWeb

CmriSeWeb/pom.xml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml

PullRequestCommitFromGabo20122019

CommitFromGabo20122019

---

CmriSeWeb/src/main/java/com/cmrise/ejb/helpers/SelectsHelper.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/WEB-INF/template/template.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateAnnotatedImageAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateIndicateImageAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateMultipleChoiceAnswer.xhtml

Commit27122918

---

CmriSeWeb/pom.xml
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/dc4mche/LeerArchivoDicomForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/helpers/SelectsHelper.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/WEB-INF/template/template.xhtml
CmriSeWeb/src/main/webapp/cmrise/dicom/LeerArchivoDicom.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/CreateCandidate.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/CreateTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/ManageCandidates.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/ManageTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExamAddCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/CreateCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/CreateQuestionCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/ManageCoreCases.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateQuestionMultipleChoiceCoreCase.xhtml

CommitFromGabo15012020

---

CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/WEB-INF/template/template.xhtml
CmriSeWeb/src/main/webapp/cmrise/admin/RolesUsuarios.xhtml
CmriSeWeb/src/main/webapp/cmrise/admin/Usuarios.xhtml

|Commit from Francisco17/01/2020

---

CmriSeWeb/src/main/webapp/cmrise/admin/RolesUsuarios.xhtml
CmriSeWeb/src/main/webapp/cmrise/admin/TablasUtilitariasValores.xhtml
CmriSeWeb/src/main/webapp/cmrise/admin/Usuarios.xhtml
CmriSeWeb/src/main/webapp/cmrise/dicom/LeerArchivoDicom.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/CreateCandidate.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/CreateTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/ManageCandidates.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/ManageTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExamAddCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/CreateCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/CreateQuestionCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/ManageCoreCases.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateQuestionMultipleChoiceCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/CreateMrq.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/ManageNewMrqs.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateAnnotatedImageAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateIndicateImageAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateMrq.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateMultipleChoiceAnswer.xhtml

Francisco:23012020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/admin/MenuForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/CreateGroupForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/ManageCandidatesForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/ManageTestExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/UpdateGroupForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/UpdateTestExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/admin/AdmonCcCandidatos.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/admin/AdmonCcCandidatosLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/admin/AdmonCcCandidatosLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/CcHdrLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/CcHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/admin/AdmonCcCandidatosDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/admin/AdmonUsuariosDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/corecases/CcHdrDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/TemplateDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/admin/AdmonCcCandidatosDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/admin/AdmonCcCandidatosV1Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/admin/AdmonCcCandidatosDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/admin/AdmonUsuariosDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/corecases/CcHdrDaoImpl.java
CmriSeWeb/src/main/webapp/WEB-INF/template/template.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/CreateCoreCaseGroup.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/ManageCandidates.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateCoreCaseGroup.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExam.xhtml

Commit21022020 from Gabo18022020

Commit21022020 from Gabo18022020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/ExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/ManageExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/UpdateFTAMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/preview/MrqPreviewForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/candidates/exams/CandCcExamenesV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandCcExamenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandCcExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandCcPreguntasHdrLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandCcPreguntasHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/MrqsPreguntasHdrLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/MrqsPreguntasHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/candidates/exams/CandCcExamenesDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/candidates/exams/CandCcPreguntasHdrDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/mrqs/MrqsPreguntasHdrDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/mrqs/MrqsPreguntasHdrV2Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/admin/AdmonCcCandidatosDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/candidates/exams/CandCcExamenesDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/candidates/exams/CandCcPreguntasHdrDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/exams/CcExamAsignacionesDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/mrqs/MrqsPreguntasHdrDaoImpl.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/WEB-INF/template/template.xhtml
CmriSeWeb/src/main/webapp/WEB-INF/template/templateCandidates.xhtml
CmriSeWeb/src/main/webapp/candidates/exams/Exam.xhtml
CmriSeWeb/src/main/webapp/candidates/exams/ManageExams.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/preview/MrqPreview.xhtml
CmriSeWeb/src/main/webapp/index.xhtml

commit22032020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/ExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/ManageMrqsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/UpdateFTAMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/preview/MrqPreviewForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/helpers/SelectsHelper.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/MrqsOpcionMultiple.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/MrqsOpcionMultipleLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/MrqsOpcionMultipleLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/mrqs/MrqsOpcionMultipleDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/mrqs/MrqsOpcionMultipleDaoImpl.java
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateQuestionFtaCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/preview/MrqPreview.xhtml

Commit23032020

---

CmriSeWeb/src/main/webapp/WEB-INF/template/topbar.xhtml
CmriSeWeb/src/main/webapp/index.xhtml

commit23032020V3

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/admin/IndexForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/admin/UserRoleFilter.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/corecases/UpdateCoreCaseForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/CreateMrqsExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/ManageMrqsExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/UpdateMrqsExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/helpers/SelectsHelper.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsExamenesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsExamenesV1Dto.java
CmriSeWeb/src/main/java/com/cmrise/utils/Utilitarios.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/WEB-INF/template/template.xhtml
CmriSeWeb/src/main/webapp/WEB-INF/web.xml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/CreateMrqsExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/ManageMrqsExams.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/UpdateMrqsExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateCoreCase.xhtml
CmriSeWeb/src/main/webapp/error.xhtml
CmriSeWeb/src/main/webapp/index.xhtml

Commit29032020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/ManageMrqsExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/UpdateMrqsExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsGrupoHdr.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsGrupoLines.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsGrupoHdrLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsGrupoHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsGrupoLinesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsGrupoLinesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/exams/MrqsGrupoHdrDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/exams/MrqsGrupoLinesDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsGrupoHdrDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsGrupoLinesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/exams/MrqsGrupoHdrDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/exams/MrqsGrupoLinesDaoImpl.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/ManageMrqsExams.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/UpdateMrqsExam.xhtml

Commit30032020V1

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/MRQsExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/ManageExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/candidates/exams/CandExamRespuestasV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/candidates/exams/CandExamenesV2.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandExamRespuestasLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandExamRespuestasLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandExamenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/candidates/exams/CandExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/candidates/exams/CandExamRespuestasDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/candidates/exams/CandExamenesDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/candidates/exams/CandExamRespuestasDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/candidates/exams/CandExamRespuestasDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/candidates/exams/CandExamenesDaoImpl.java
CmriSeWeb/src/main/webapp/candidates/exams/MRQsExam.xhtml
CmriSeWeb/src/main/webapp/candidates/exams/ManageExams.xhtml
CmriSeWeb/src/main/webapp/index.xhtml

Commit05042020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/corecases/preview/CoreCasePreviewForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/CreateGroupForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/UpdateTestExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/helpers/SelectsHelper.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/CcExamAsignaciones.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/CcExamenes.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/CcHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/CcPreguntasHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/exams/CcExamAsignacionesDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/CcExamAsignacionesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/CcExamenesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/exams/CcExamAsignacionesDaoImpl.java
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/CreateTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/preview/CoreCasePreview.xhtml

commit 14042020v1

---

CmriSeWeb/pom.xml
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/CoreCasesExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/ManageExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/AssignCoreCasesCandidatesForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/UpdateGroupForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/corecases/UpdateTestExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/admin/AdmonUsuariosRolesV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosRolesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/admin/AdmonUsuariosRolesDaoImpl.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/candidates/exams/CoreCasesExam.xhtml
CmriSeWeb/src/main/webapp/candidates/exams/ManageExams.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/AssignCoreCasesCandidates.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/corecases/UpdateTestExam.xhtml

Commit 15042020V1

---

CmriSeWeb/pom.xml
CmriSeWeb/src/main/java/com/cmrise/dicom/image/DicomImageReaderService.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/CoreCasesExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/candidates/exams/ManageExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/corecases/UpdateQuestionFtaCoreCaseForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/corecases/preview/CoreCasePreviewForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/corecases/CcPreguntasFtaV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/corecases/img/CcImagenes.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/corecases/img/CcImagenesGrp.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/CcHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/img/CcImagenesGrpLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/img/CcImagenesGrpLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/img/CcImagenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/corecases/img/CcImagenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamAsignacionesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamAsignacionesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/CcExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/corecases/img/CcImagenesDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/corecases/img/CcImagenesGrpDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/corecases/img/CcImagenesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/corecases/img/CcImagenesGrpDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/corecases/img/CcImagenesDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/corecases/img/CcImagenesGrpDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/utils/Utilitarios.java
CmriSeWeb/src/main/webapp/candidates/exams/CoreCasesExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/UpdateQuestionFtaCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/preview/CoreCasePreview.xhtml

Commit 18042020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/CreateMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/ManageMrqsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/UpdateFTAMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsGrupoLinesV2.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/MrqsPreguntasHdrV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsGrupoLinesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/MrqsPreguntasHdrLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsGrupoLinesV1Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsGrupoLinesV2Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/mrqs/MrqsPreguntasHdrDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/mrqs/MrqsPreguntasHdrV1Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/mrqs/MrqsPreguntasHdrV2Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/mrqs/MrqsPreguntasHdrDaoImpl.java
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/CreateCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/corecases/CreateQuestionCoreCase.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/CreateMrq.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/ManageNewMrqs.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml

Commit 04052020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/ManageMrqsExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/preview/PreviewExamenReactivosForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsExamenes.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsGrupoHdr.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsGrupoLines.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/MrqsPreguntasFtaV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/MrqsPreguntasHdrV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsExamenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/mrqs/MrqsPreguntasFtaDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/mrqs/MrqsPreguntasFtaDaoImpl.java
CmriSeWeb/src/main/webapp/WEB-INF/.faces-config.xml.jsfdia
CmriSeWeb/src/main/webapp/WEB-INF/faces-config.xml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/ManageMrqsExams.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/preview/PreviewExamenReactivos.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/preview/MrqPreview.xhtml

Commit 07052020

---

CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/preview/PreviewExamenReactivos.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml

Commit06052020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/admin/AdmonExamenesDetailForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/CreateMrqsExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/ManageMrqsExamsForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/exams/mrqs/UpdateMrqsExamForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/exams/MrqsExamenes.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsExamenesLocal.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/exams/MrqsExamenesLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/exams/MrqsExamenesDao.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsExamenesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/exams/MrqsExamenesV1Dto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/exams/MrqsExamenesDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/utils/Utilitarios.java
CmriSeWeb/src/main/webapp/cmrise/admin/AdmonMaterias.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/CreateMrqsExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/ManageMrqsExams.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/UpdateMrqsExam.xhtml
CmriSeWeb/src/main/webapp/cmrise/examenes/mrqs/preview/PreviewExamenReactivos.xhtml

Commit 06052020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/UpdateFTAMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/img/MrqsImagenes.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/img/MrqsImagenesGrpLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/mrqs/img/MrqsImagenesDto.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/mrqs/img/MrqsImagenesDaoImpl.java
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/preview/MrqPreview.xhtml

Commit 12052020

---

CmriSeWeb/pom.xml
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/UpdateFTAMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/preview/MrqPreviewForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/AnotacionesCorImg.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/MrqsPreguntasFtaV1.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/RespCorrectReactCorImg.java
CmriSeWeb/src/main/java/com/cmrise/ejb/model/mrqs/RespReactCorImg.java
CmriSeWeb/src/main/java/com/cmrise/ejb/services/mrqs/MrqsPreguntasFtaLocalImpl.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dto/mrqs/MrqsPreguntasFtaDto.java
CmriSeWeb/src/main/java/com/cmrise/utils/Utilitarios.java
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/CreateMrq.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/UpdateFreeTextAnswer.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/preview/MrqPreview.xhtml
CmriSeWeb/src/main/webapp/resources/js/cmrise/reactivos/UpdateReactivosImgCor.js
CmriSeWeb/src/main/webapp/resources/js/cmrise/reactivos/UpdateReactivosImgCorBkp18062020.js
CmriSeWeb/src/main/webapp/resources/js/cmrise/reactivos/UpdateReactivosImgSen.js
CmriSeWeb/src/main/webapp/resources/js/cmrise/reactivos/UpdateReactivosPreviewBkp18062020.js

Commit23062020

---

CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/UpdateFTAMrqForm.java
CmriSeWeb/src/main/java/com/cmrise/ejb/backing/mrq/preview/MrqPreviewForm.java
CmriSeWeb/src/main/java/com/cmrise/jpa/dao/mrqs/MrqsCorrelacionColumnaPair.java
CmriSeWeb/src/main/java/com/cmrise/jpa/jdbc/mrqs/MrqsOpcionMultipleDaoImpl.java
CmriSeWeb/src/main/java/com/cmrise/utils/Utilitarios.java
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/MatchingColumns.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/MatchingColumnsPrev.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/MatchingColumnsPrev2.xhtml
CmriSeWeb/src/main/webapp/cmrise/preguntas/mrqs/MatchingColumnsPrevResults.xhtml

2.Puntuación Proporcional
3.Reactivo de correlación de columnas

1.Modificaciones en Correlación de columnas

---

CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/backing/exams/mrqs/AssignMrqsCandidatesForm.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/backing/exams/mrqs/CreateMrqsCandidatesForm.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/model/admin/AdmonUsuarios.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/model/admin/AdmonUsuariosRolesV1.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/model/candidates/exams/CandExamenesV1.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosLocal.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosLocalImpl.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosRolesLocal.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/services/admin/AdmonUsuariosRolesLocalImpl.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/services/candidates/exams/CandExamenesLocal.java
CmriSeWeb-1.0/src/main/java/com/cmrise/ejb/services/candidates/exams/CandExamenesLocalImpl.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/dao/admin/AdmonUsuariosDao.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/dao/admin/AdmonUsuariosRolesDao.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/dao/candidates/exams/CandExamenesDao.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/dto/admin/AdmonUsuariosRolesV1Dto.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/dto/candidates/exams/CandExamenesV1Dto.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/jdbc/admin/AdmonUsuariosDaoImpl.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/jdbc/admin/AdmonUsuariosRolesDaoImpl.java
CmriSeWeb-1.0/src/main/java/com/cmrise/jpa/jdbc/candidates/exams/CandExamenesDaoImpl.java
CmriSeWeb-1.0/src/main/webapp/cmrise/examenes/mrqs/AssignMrqsCandidates.xhtml
CmriSeWeb-1.0/src/main/webapp/cmrise/examenes/mrqs/CreateMrqsCandidates.xhtml

Filters added
2 Views altered: 
############################################
USE [CMRISE]
GO
/****** Object:  View [dbo].[CAND_EXAMENES_V1]    Script Date: 23/12/2020 03:44:31 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   VIEW [dbo].[CAND_EXAMENES_V1] AS
SELECT CE.[NUMERO]
,CE.[NUMERO_USUARIO]
,CE.[NUMERO_EXAMEN]
,EX.DESCRIPCION
,CE.[TIPO]
,CE.[ESTATUS]
,CE.[CREADO_POR]
,CE.[FECHA_CREACION]
,AD.[ACTUALIZADO_POR]
,AD.[FECHA_ACTUALIZACION]
,AURV1.MATRICULA
,AURV1.NOMBRE_USUARIO
,AURV1.APELLIDO_PATERNO
,AURV1.APELLIDO_MATERNO
,AURV1.NOMBRE_COMPLETO_USUARIO
,AURV1.NOMBRE_ROL
,AURV1.DESCRIPCION_ROL
,AURV1.CURP
,ISNULL((SELECT SUM(ISNUll(CER.PUNTUACION,0)) FROM dbo.[CAND_EXAM_RESPUESTAS] CER WHERE CER.NUMERO_CAND_EXAMEN = CE.NUMERO ),0) TOTAL_PUNTUACION
,(select …

Daniel fdez contrib
